# Do NOT update manually; changes here will be overwritten by Copier
_commit: v1.11.1
_src_path: gh:oca/oca-addons-repo-template
ci: Travis
dependency_installation_mode: PIP
generate_requirements_txt: true
github_check_license: true
github_enable_codecov: true
github_enable_makepot: true
github_enable_stale_action: true
github_enforce_dev_status_compatibility: true
include_wkhtmltopdf: false
odoo_version: 14.0
org_name: Odoo Community Association (OCA)
org_slug: OCA
rebel_module_groups: []
repo_description: This project aim to deal with modules related to manage account
    closing.
repo_name: Addons related to manage account closing
repo_slug: account-closing
repo_website: https://github.com/OCA/account-closing
travis_apt_packages: []
travis_apt_sources: []

