[project]
name = "odoo-addons-oca-account-closing"
version = "19.0.20260616.0"
dependencies = [
    "odoo-addon-account_fiscal_year_closing==19.0.*",
    "odoo-addon-account_invoice_start_end_dates==19.0.*",
]
classifiers=[
    "Programming Language :: Python",
    "Framework :: Odoo",
    "Framework :: Odoo :: 19.0",
]
